development:
  adapter: sqlite3
  database: db/dev_whispering.sqlite3

test:
  adapter: sqlite3
  database: db/test_whispering.sqlite3

production:
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
  database: prod_whispering

